name: Test

on:
    workflow_call:
        inputs:
            runs-on:
                type: string
                default: ubuntu-latest
                required: true

jobs:
    # exports:
    #     runs-on: ${{ inputs.runs-on }}
    #     strategy:
    #         fail-fast: true
    #         matrix:
    #             script:
    #                 - ./e2e/scripts/exports/default-arrow-async.ts
    #                 - ./e2e/scripts/exports/default-arrow.ts
    #                 - ./e2e/scripts/exports/default-function-async.ts
    #                 - ./e2e/scripts/exports/default-function.ts
    #                 - ./e2e/scripts/exports/main-const-async.ts
    #                 - ./e2e/scripts/exports/main-const.ts
    #                 - ./e2e/scripts/exports/main-function-async.ts
    #                 - ./e2e/scripts/exports/main-function.ts
    #     steps:
    #         - uses: actions/checkout@v3
    #         - uses: actions/download-artifact@v3
    #           with:
    #               name: dist
    #               path: dist

    #         - name: Run Test Script
    #           id: run-test-script
    #           uses: ./
    #           with:
    #               path: ${{ matrix.script }}

    #         - name: Check Test Result
    #           shell: bash
    #           run: |
    #               test ${{ steps.run-test-script.outputs.result }} = "hello, world"

    fail-in-script:
        runs-on: ${{ inputs.runs-on }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Run Test Script
              id: run-test-script
              continue-on-error: true
              uses: ./
              with:
                  path: ./e2e/scripts/failure.ts

            - name: Check Test Result
              shell: bash
              run: |
                  test ${{ steps.run-test-script.outcome }} = "failure"

    args:
        runs-on: ${{ inputs.runs-on }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Run Test Script
              id: run-test-script
              uses: ./
              with:
                  path: ./e2e/scripts/args.ts

    zx:
        runs-on: ${{ inputs.runs-on }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Run Test Script
              id: run-test-script
              uses: ./
              with:
                  path: ./e2e/scripts/zx.ts

            - name: Check Test Result
              shell: bash
              run: |
                  test ${{ steps.run-test-script.outputs.result }} = "hello, world"

    node_modules:
        runs-on: ${{ inputs.runs-on }}
        strategy:
            fail-fast: true
            matrix:
                module:
                    - "@shqld/github-acript-test-cjs"
                    - "@shqld/github-acript-test-cjs@1"
                    - "@shqld/github-acript-test-cjs@^1.0.5"
                    - "@shqld/github-acript-test-cjs@1.x"
                    - "@shqld/github-acript-test-cjs@1.0.5"
        permissions:
            contents: read
            packages: read
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
                  registry-url: "https://npm.pkg.github.com"
                  scope: "@shqld"

            - name: Run Test Script
              id: run-test-script
              uses: ./
              with:
                  node_modules: |
                      ${{ matrix.module }}
                  path: ./e2e/scripts/node_modules.ts
                  registry-url: https://npm.pkg.github.com
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Check Test Result
              shell: bash
              run: |
                  test ${{ steps.run-test-script.outputs.result }} = "hello, world"

            - name: Check Installed Modules
              shell: bash
              run: |
                  yarn_list=$(yarn list)

                  echo $yarn_list | grep @shqld/github-acript-test-cjs@1

    inputs:
        runs-on: ${{ inputs.runs-on }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: dist
                  path: dist

            - name: Run Test Script / Both inputs
              id: run-test-script-both-inputs
              continue-on-error: true
              uses: ./
              with:
                  path: some_path
                  script: some_script

            - name: Run Test Script / No inputs
              id: run-test-script-no-inputs
              continue-on-error: true
              uses: ./

            - name: Run Test Script / Only path
              id: run-test-script-only-path
              continue-on-error: true
              uses: ./
              with:
                  path: ./e2e/scripts/success.ts

            - name: Run Test Script / Only script
              id: run-test-script-only-script
              continue-on-error: true
              uses: ./
              with:
                  script: |
                      process.exit(0)

            - name: Check Test Result
              shell: bash
              run: |
                  test ${{ steps.run-test-script-both-inputs.outcome }} = "failure"
                  test ${{ steps.run-test-script-no-inputs.outcome }} = "failure"
                  test ${{ steps.run-test-script-only-path.outcome }} = "success"
                  test ${{ steps.run-test-script-only-script.outcome }} = "success"
